# Generated by Django 5.0.6 on 2024-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
