# Generated by Django 5.0.6 on 2024-07-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mensaje',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
