# Generated by Django 5.0.6 on 2024-07-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_member_mensaje_alter_member_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='tarifa',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experiencia',
            field=models.TextField(),
        ),
    ]
